#when to use proxy to link some web, you should set your web browser use proxy also.
#and make sure localhost is in no_proxy list.
#so you can add this line below when using google_chrome on linux
#     export no_proxy=http://127.0.0.1
development:
  phantomjs_full_path : d:/work/bin/phantomjs.exe
  use_proxy : no
  http_proxy :  127.0.0.1:8118
test:
  phantomjs_full_path : d:/work/bin/phantomjs.exe
  use_proxy : yes
  http_proxy : 127.0.0.1:8118